version: '3'

services:
  nginx:
    build: ./nginx
    restart: always
    image: nginximage 
    ports:
      - "8888:80"
    depends_on:
      - node_service
    links:
      - node_service

  node_service:
    build: ./api
    restart: always
    image: nodeimage
    ports:
      - "3000:3000"
    environment:
        MYSQL_USER: "${DB_USER}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
    depends_on:
      - db 
    links:
      - db

  db:
    image: dbimage
    build: ./db/
    restart: always
    container_name: containerdb
    environment:
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
